spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/notifydb
  config:
    import: configserver:http://localhost:8888
server:
  port: 8052
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/