spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/customerdb
  config:
    import: configserver:http://localhost:8888
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/