spring:
  application:
    name: customer-service

  data:
    mongodb:
      #uri:mongodb://admin:secret@mongodb:27017/customerdb?authSource=admin
      #uri: mongodb://admin:secret@localhost:27017/customerdb?authSource=admin
      uri: mongodb://localhost:27017/customerdb

  cloud:
    config:
      enabled: false   # ? disables config server completely

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
