spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/paymentdb
  config:
    import: configserver:http://localhost:8888
server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/