spring:
  application:
    name: reservation-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/reservationdb
  config:
    import: configserver:http://localhost:8888
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/