spring:
  application:
    name: hotel-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/hoteldb
  config:
    import: configserver:http://localhost:8888
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/